project_id = "gfyeuhfapscxfvjnrssn"

[functions.generate-ideas]
verify_jwt = false

[functions.generate-captions]
verify_jwt = false

[functions.repurpose-project]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.generate-30day-plan]
verify_jwt = false

[functions.creative-studio]
verify_jwt = false

[functions.generate-image]
verify_jwt = false
